### ISSUE TITLE
{"Error":"Runtime.ImportModuleError","Cause":"{\"errorMessage\": \"Unable to import module 'initializer': No module named 'aws_lambda_logging'\", \"errorType\": \"Runtime.ImportModuleError\"}"}

### ISSUE THREAD

**Issue by TrTx01** [aws-samples/aws-lambda-etl-ref-architecture#2]
Hello,

I am getting the following error in my AWS Notification Message:

{"Error":"Runtime.ImportModuleError","Cause":"{\"errorMessage\": \"Unable to import module 'initializer': No module named 'aws_lambda_logging'\", \"errorType\": \"Runtime.ImportModuleError\"}"}

See attachment for error email. 
Is there anyway I can fix this? Please let me know.

Also - FYI, to get this CloudFromation stack deployed, I had to add the 2 permissions to the User as the 4 policies mentioned by you in this example were not sufficient:

1. AmazonSNSFullAccess
2. AWSStepFunctionsFullAccess

You can update your documentation accordingly.
Thank you.

![Screen Shot 2020-11-09 at 8 44 22 AM](https://user-images.githubusercontent.com/41862060/98497359-c2cc2000-2269-11eb-8a79-167493ecc95b.png)

**Comment by arthi-j** [comment]
@TrTx01 All Lambda functions have a dependency on `aws-lambda-logging` library for logging. You can see this specified in the `requirements.txt` file within each lambda folder under `src`. If you run `sam build --use-container`, the dependencies should get packaged. Can you confirm you have done this?

As for your question on the permissions, can you clarify which policies you are referring to? To deploy the template as an IAM user, you will need permissions to create all the resources created by the template. The template itself defines permissions for Lambda and Step Functions.

**Comment by TrTx01** [comment]
Hello @arthi-j Thank you for your quick response and appreciate your patience with a rookie like me :-)

I re-ran all the steps for build, package, deploy and test, please see attached screenshots of the same. Now I am getting a new error. Please see that file too marked as Results-Error-Email.png. If you can help here, that would be great?

Also, for the permission, I re-read the instructions [page](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install-mac.html) and looks like the initial permissions of 4 policies (AWSCloudFormationFullAccess, IAMFullAccess, AWSLambdaFullAccess and AmazonAPIGatewayAdministrator) were for the "Hello World" sample application. Sorry about this confusion. To run your code, like I said before, I had to add AmazonSNSFullAccess and AWSStepFunctionsFullAccess for it to not give me errors.

Is there a common place where I can see all the policies that I need to add for the IAM User as there are too many of them with variants for the same resource permission. You have said "The template itself defines permissions for Lambda and Step Functions.", how do I read this and apply the policies? Please let me know. Thank you.

![Results_Error_Email](https://user-images.githubusercontent.com/41862060/98693287-19cf1380-2396-11eb-9cb0-9069713712f9.png)
![AWS-Testing-Example](https://user-images.githubusercontent.com/41862060/98693294-1cca0400-2396-11eb-97f9-a396f7da605c.png)
![AWS-Sam-Deploy2](https://user-images.githubusercontent.com/41862060/98693298-1d629a80-2396-11eb-85b7-27905f3aa43d.png)
![AWS-Sam-Deploy1](https://user-images.githubusercontent.com/41862060/98693300-1e93c780-2396-11eb-8fd6-e5e45e03a317.png)
![AWS-Sam-Package](https://user-images.githubusercontent.com/41862060/98693306-205d8b00-2396-11eb-8b66-2be1a028ec46.png)
![AWS-Sam-Build](https://user-images.githubusercontent.com/41862060/98693307-20f62180-2396-11eb-9a67-ed7fe22edece.png)

**Comment by TrTx01** [comment]
Ok - I've done some initial research and looks like that the Lambda function has a timeout which is expiring and therefore did not return an error type. I could be wrong, but I see 4 timeout variables in the SAM template with values like Timeout: 3 for the Download Function, Timeout: 60 for the Process Function, Timeout 15 for the Aggregate Function and Timeout: 15 for the Delete Function. I will try to double these values and run it again. Now I need to work out how to update the SAM Template and retest this entire thing.....

**Comment by TrTx01** [comment]
Ok - I am getting closer to resolving it but still need more time. I changed the Timeout for the Process Function from the default 60 sec to 120 and then to 240 secs. It still timed out. See attachment. But now I will give it 900 and check to why the Process function is timing out.
![Screen Shot 2020-11-11 at 8 21 04 PM](https://user-images.githubusercontent.com/41862060/98826903-45b4cc80-245c-11eb-98df-1db138388501.png)

**Comment by TrTx01** [comment]
@arthi-j - Tried it with 900 seconds too but the Task has timed out. Can't figure this out. Need your help please?

Error: 2020-11-12T06:55:54.731Z 6b157d52-e599-4bce-9e1d-c9af1cc51ec2 Task timed out after 901.26 seconds

**Comment by arthi-j** [comment]
Thanks for flagging this. I was able to recreate the timeouts. The S3 download from openaq bucket seems to be taking longer. Can you update the `CHUNK_SIZE` environment variable for the Initializer function to 12 and rerun? This will basically halve the number of files passed to each invocation of Process function. I have also increased the timeout for Process function to 3 minutes.

**Comment by TrTx01** [comment]
Hello @arthi-j - I tried again with CHUNKSize Default as 12 and also kept the Process Function timeout to 900. I am presuming that this number is in seconds, so after 15 mins, I got the same error email. Please see screenshots of the parameters from the SAM template and the timeout error from the logs. Hope you hear back from you. Thank you!

![Screen Shot 2020-11-13 at 10 31 44 PM](https://user-images.githubusercontent.com/41862060/99099785-efcd5980-2600-11eb-95fe-66e5c3abdcca.png)
![Screen Shot 2020-11-13 at 10 34 39 PM](https://user-images.githubusercontent.com/41862060/99099798-f4920d80-2600-11eb-9b34-8a506d4b426b.png)

**Comment by arthi-j** [comment]
Did you redeploy the template after updating it? An easier way is to directly update the parameter on lambda console.

**Comment by TrTx01** [comment]
@arthi-j - yes, I redeployed it and still it was timing out. Is there anything else I can try as I really wanted to see this work?

Thx

**Comment by arthi-j** [comment]
@TrTx01 I am closing this. Based on my testing today, memory setting of 1 GB and timeout of 3 min works fine.
